### ISSUE TITLE
failed to find Build Tools revision 15.0.0

### ISSUE THREAD

**Issue by code-by** [micabe/react-native-share-instagram#2]
Hello!
Where I can now get this old version of build tools?

```
$ react-native run-android
...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@micabe/react-native-share-instagram'.
> failed to find Build Tools revision 15.0.0

```

**Comment by micabe** [comment]
Hi @code-by thanks for raising this issue. build tools have been updated to match SDK version (23).
available in the new release react-native-share-instagram@1.0.9
